### ISSUE TITLE
why does parsing as `Json array` try to convert to a union case?

### ISSUE THREAD

**Issue by hesxenon** [Zaid-Ajaj/Fable.SimpleJson#108]
```fsharp
let data = """[["foo", "bar"]]""" // Fable.Remoting.Client sends this for `("foo", "bar")`
Json.parseAs<Json array> data // throws "Case foo was not valid, expected one of [JNumber, JString, JBool, JNull, JArray, JObject]"
```
how can I convert this to a `Json array`?

**Comment by Zaid-Ajaj** [comment]
Hi @hesxenon the `Json.parseAs` API is made for automatic parsing and converting into F# types such as records, unions, maps, etc. If you want the underlying JSON AST (i.e. `Json` type) you can use `SimpleJson.parse`:
```fsharp
match SimpleJson.parse """[["foo", "bar"]]""" with
| JArray values -> ... 
| anythingElse -> 
```

> I think we can make `Json.parseAs<Json array> data` work by special-casing the `Json` type but that's an extra

Also also, can you explain to me why you need this? Maybe I can help you implement it. 
 if Fable.Remoting.Client sends `("foo", "bar")` you should be able to use automatic parsing with 
```fsharp
Json.parseAs<string * string> data
```

**Comment by hesxenon** [comment]
I created a giraffe-like API for node.js (Fable.Node.Okapi, just a private repo for now, name is not taken) and I would like to create a "Fable.Remoting.Okapi" backend for this.

As I understood it, I need a type to correctly parse e.g. a DU (with `Convert.fromJsonAs jsonValue typeInfo`). Now, I have the types but I don't know how I get the json values when they're wrapped in an array.

I guess I could then do something like
```fsharp
match SimpleJson.parse """[["foo", "bar"]]""", typeInfos with
| JArray [|arg0|], [|type0|] -> Convert.fromJsonAs arg0 type0
// repeat for up to 7 cases, fail for other top level types?
```
?

Is there a "cleaner" way to do this?

EDIT:
> I think we can make Json.parseAs<Json array> data work by special-casing the Json type but that's an extra

did you mean to write this here? I can't make sense of it ATM, but maybe I'm just being dense...

**Comment by Zaid-Ajaj** [comment]
> I created a giraffe-like API for node.js (Fable.Node.Okapi, just a private repo for now, name is not taken) and I would like to create a "Fable.Remoting.Okapi" backend for this.

That sounds awesome! Love the idea of `Fable.Remoting.Okapi` 💯 


> As I understood it, I need a type to correctly parse e.g. a DU (with Convert.fromJsonAs jsonValue typeInfo). Now, I have the types but I don't know how I get the json values when they're wrapped in an array.
> 
> I guess I could then do something like
> 
> match SimpleJson.parse """[["foo", "bar"]]""", typeInfos with
> | JArray [|arg0|], [|type0|] -> Convert.fromJsonAs arg0 type0
> // repeat for up to 7 cases, fail for other top level types?
> ?

Yeah something like this would do. [Fable.Giraffe](https://github.com/dbrattli/Fable.Giraffe/blob/main/src/Remoting.fs) has implemented a similar idea for Fable-python in which the code is very similar to what you would need for nodejs because Fable.Giraffe uses Fable.SimpleJson.Python (port of Fable.SimpleJson with the exact same API)

**Comment by hesxenon** [comment]
I see, well, if there isn't a simpler way I guess I'll do it like that. 

Though I still feel there must be a way to only parse the top level... you wrote somewhere that SimpleJson is using a parser combinator library, no? Shouldn't it be possible with this?

I just don't like the code that's being generated by "excessive" pattern matching, it's quite huge...

As for `Fable.Remoting.Okapi`: I'd love some feedback on this, if I write up a Readme and make it public would you be willing to have a look at it? It's still pretty much WIP but the basics should be working after this. I think.

**Comment by Zaid-Ajaj** [comment]
> Though I still feel there must be a way to only parse the top level... you wrote somewhere that SimpleJson is using a parser combinator library, no? Shouldn't it be possible with this?

I don't really understand what you mean by "only parse top level" 😅 

> I'd love some feedback on this, if I write up a Readme and make it public would you be willing to have a look at it? 

Sure thing!

**Comment by hesxenon** [comment]
> top level

after trying to formulate an answer to this I see that `SimpleJson.parse` already does what I mean. I thought that if I have a valid JSON structure it should be possible to parse this as a `Json array` but an array itself is already a `Json` value... which is where the pattern matching comes into play. I guess I wanted to have something between `parse` and `parseAs` in the sense that it shouldn't try to convert to F# structures, but this probably is just unnecessary complexity for very little merit.

I think we can close this issue :) thanks for taking the time to explain these things to me :+1:

**Comment by hesxenon** [comment]
as for [`Fable.Remoting.Okapi`](https://gitlab.com/hesxenon/fable.remoting.okapi/-/tree/main) - I'd love some review, but please keep in mind that this project is very much "it works on my machine" for now :)
