### ISSUE TITLE
Simple json throws an error on an otherwise valid JSON

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/Fable.SimpleJson#109]
When trying to use a an object like this in my project, 

```fsharp

    module Dto =

        open System


        module ValueUnit =

            type Dto() =
                member val Value : string [] = [||] with get, set
                member val Unit = "" with get, set
                member val Group = "" with get, set
                member val Short = true with get, set
                member val Language = "" with get, set

            let dto () = Dto()


        module OrderVariable =


            type VarDto () =
                member val Min : ValueUnit.Dto option = None with get, set
                member val MinIncl = false with get, set
                member val Incr : ValueUnit.Dto option = None with get, set
                member val Max : ValueUnit.Dto option = None with get, set
                member val MaxIncl = false with get, set
                member val Vals : ValueUnit.Dto option = None with get, set


            type Dto () =
                member val Name = "" with get, set
                member val Constraints = VarDto () with get, set
                member val Variable = VarDto () with get, set


            let dto () = Dto ()


        module Prescription =


            type Dto () =
                member val IsContinuous = false with get, set
                member val IsDiscontinuous = false with get, set
                member val IsTimed = false with get, set
                member val Frequency = OrderVariable.dto () with get, set
                member val Time = OrderVariable.dto () with get, set


            let dto () = Dto ()


        module Dose =


            type Dto () =
                member val Quantity = OrderVariable.dto () with get, set
                member val PerTime = OrderVariable.dto () with get, set
                member val Rate = OrderVariable.dto () with get, set
                member val Total = OrderVariable.dto () with get, set
                member val QuantityAdjust = OrderVariable.dto () with get, set
                member val PerTimeAdjust = OrderVariable.dto () with get, set
                member val RateAdjust = OrderVariable.dto () with get, set
                member val TotalAdjust = OrderVariable.dto () with get, set


            let dto () = Dto ()


        module Item =

            type Dto () =
                member val Name = "" with get, set
                member val ComponentQuantity = OrderVariable.dto () with get, set
                member val OrderableQuantity = OrderVariable.dto () with get, set
                member val ComponentConcentration = OrderVariable.dto () with get, set
                member val OrderableConcentration = OrderVariable.dto () with get, set
                member val Dose = Dose.dto () with get, set



        module Component =


            type Dto () =
                member val Id = "" with get, set
                member val Name = "" with get, set
                member val Shape = "" with get, set
                member val ComponentQuantity = OrderVariable.dto () with get, set
                member val OrderableQuantity = OrderVariable.dto () with get, set
                member val OrderableCount = OrderVariable.dto () with get, set
                member val OrderQuantity = OrderVariable.dto () with get, set
                member val OrderCount = OrderVariable.dto () with get, set
                member val OrderableConcentration = OrderVariable.dto () with get, set
                member val Dose = Dose.dto () with get, set
                member val Items : Item.Dto [] = [||] with get, set



        module Orderable =


            type Dto () =
                member val Name = "" with get, set
                member val OrderableQuantity = OrderVariable.dto () with get, set
                member val OrderQuantity = OrderVariable.dto () with get, set
                member val OrderCount = OrderVariable.dto () with get, set
                member val DoseCount = OrderVariable.dto () with get, set
                member val Dose = Dose.dto () with get, set
                member val Components : Component.Dto [] = [||] with get, set


            let dto () = Dto ()


        type Dto() =
            member val Id = "" with get, set
            member val Adjust = OrderVariable.dto () with get, set
            member val Orderable = Orderable.dto () with get, set
            member val Prescription = Prescription.dto () with get, set
            member val Route = "" with get, set
            member val Duration = OrderVariable.dto () with get, set
            member val Start = DateTime.Now with get, set
            member val Stop : DateTime option = None with get, set


    type Scenario =
        {
            Shape : string
            DoseType : string
            Prescription : TextItem[]
            Preparation : TextItem[]
            Administration : TextItem[]
            Dto: Dto.Dto
        }

```

simple json throws the following error:

> Error: Cannot convert {"Adjust":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"Duration":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"Id":"","Orderable":{"Components":[],"Dose":{"PerTime":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"PerTimeAdjust":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"Quantity":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"QuantityAdjust":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"Rate":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"RateAdjust":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"Total":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"TotalAdjust":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}}},"DoseCount":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"Name":"","OrderCount":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"OrderQuantity":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"OrderableQuantity":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}}},"Prescription":{"Frequency":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}},"IsContinuous":false,"IsDiscontinuous":false,"IsTimed":false,"Time":{"Constraints":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null},"Name":"","Variable":{"Incr":null,"Max":null,"MaxIncl":false,"Min":null,"MinIncl":false,"Vals":null}}},"Route":"","Start":"2023-04-17T12:15:33.0686520Z","Stop":null} to Shared.Types.Dto.Dto
>     at String.js:134:15
>     at String.js:233:20
>     at Convert_fromJsonAs (Json.Converter.fs.js:1746:73)
>     at Json.Converter.fs.js:1511:32
>     at map (Array.js:70:21)
>     at Convert_fromJsonAs (Json.Converter.fs.js:1475:32)
>     at Json.Converter.fs.js:1439:52
>     at folder (List.js:638:34)
>     at fold (List.js:397:15)
>     at map (List.js:642:18)
>

**Comment by Zaid-Ajaj** [comment]
Hi @halcwb unfortunately SimpleJson cannot handle classes like 
```fs
        module ValueUnit =

            type Dto() =
                member val Value : string [] = [||] with get, set
                member val Unit = "" with get, set
                member val Group = "" with get, set
                member val Short = true with get, set
                member val Language = "" with get, set

            let dto () = Dto()
```
_Records_ are supported instead
```fs
module ValueUnit = 
  type Dto = { 
      Value : string []
      Unit : string
      Group : string
      Short : bool
      Language : string
  }

  let dto() = {
    Value = [| |]
    Unit = ""
    Group = ""
    Short = true
    Language = ""
  }
```
