### ISSUE TITLE
Cannot parse Unicode literals.

### ISSUE THREAD

**Issue by Nobuhisa** [Zaid-Ajaj/Fable.SimpleJson#110]
I use this library in my job in Japan. Thanks for your cool work!

I found a small bug in the json parser.
If a json value contains Unicode literals, the parser throws an exception.

```
open Fable.Core.JS
open Fable.SimpleJson


let input1 = """
    {"sushi": "🍣"}
"""

let input2 = """
    {"sushi": "\uD83C\uDF63"}
"""

console.log("🍣" = "\uD83C\uDF63")  // true
console.log(SimpleJson.parse input1) // ok
console.log(SimpleJson.parse input2) // error
```

When I received data containing Emojis from an external server using Fable.SimpleHttp and attempted to parse it, this exception was thrown.

**Comment by Zaid-Ajaj** [comment]
Hi @Nobuhisa appreciate the kind words 🙏 I believe if you used `SimpleJson.parseNative` it should work, `SimpleJson.parse` uses a custom implementation and parser whereas `SimpleJson.parseNative` falls back to the native `JSON.parse` functionality in JS so it should work just fine 😄

**Comment by Nobuhisa** [comment]
Excuse me, I didn't try `parseNative`.
I was able to parse emojis successfully!
Thanks for your advice 🙏
