### ISSUE TITLE
Explain the motivation for using Fable.SimpleJson

### ISSUE THREAD

**Issue by pkese** [Zaid-Ajaj/Fable.SimpleJson#16]
While migrating to Fable2, I'm trying to figure out whether I should use Fable.SimpleJson or Toth.Json for my project.

The documentation isn't very helpful in this regard (please don't take this as a criticism, but rather as a suggestion on how to improve the project).

As a potential visitor I'd be more interested what the library does for me and why I should use this particular library rather than some other library. Also I'm not experienced enough to be able to decide if the library is right for me, based on the information that it was "written using parser combinators from Fable.Parsimmon."

It would be really nice if the README would explain somewhere right at the top a two-sentence elevator pitch that would explain the intent and target audience.
I'd recommend the bullets in http://elevatorpitchessentials.com/essays/CrossingTheChasmElevatorPitchTemplate.html (including caveats below) as a general direction guideline.

Btw, thanks for all of your F# contributions. They are really great.

**Comment by pkese** [comment]
Hi @Zaid-Ajaj 

Thank you very much for your detailed reply.
If I may suggest, I'd write the first paragraph approximately so (I hope I understood you correctly, ... feel free to use, abuse or ignore):

# Fable.SimpleJson

A simple lightweight library for dealing with generic JSON data in Fable projects.

It will help you deal with foreign JSON data when you need to either:
- convert between JSON and your own F# data types (with optional manual intervention), or
- parse JSON into a generic JSON-tree data structure and manipulate or transform that tree using F# pattern matching.

Compared to [Toth.Json](https://mangelmaxime.github.io/Thoth/json/v2/decode.html):
- both libraries provide equal functionality for dealing with automatic JSON to F# conversion (i.e. `Json.parseAs<T>` and `Json.stringify`),
- when dealing with manual JSON to F# type mapping, **Fable.SimpleJson** is focusing on easiness and simplicity, while **Toth.Json** is focusing on expressivity and functional composability.

**Fable.SimpleJson** is being used in [Fable.Remoting](https://github.com/Zaid-Ajaj/Fable.Remoting) (you may already have it installed). It is written using parser combinators from [Fable.Parsimmon](https://github.com/Zaid-Ajaj/Fable.Parsimmon).

**Comment by pkese** [comment]
...also, in the role of a library user, I'd be interested:
- is there some default or suggested way of dealing with discriminated unions (DU),
- can I fiddle with the way DUs get serialized and deserialized,
- is there some special support for option types (e.g. does `null` automatically get converted into `None` when parsing and vice versa when stringifying).

Sorry for bugging you with this stuff. Please stop me, before you get irritated.

**Comment by Zaid-Ajaj** [comment]
> Sorry for bugging you with this stuff. Please stop me, before you get irritated.

No not at all, I really appreciate your suggestions! documentation is always hard to get right, especially with different options available in the ecosystem and I like the way you presented the alternative. I will try to update soonish when time permits. 

As for your other questions

> is there some default or suggested way of dealing with discriminated unions (DU),

Do you mean how to deserialize them? here are a couple of examples:
```fs
type Value = 
  | One 
  | Two of int
  | Three of int * string 

"""
[
   { "Two": 20 }, // Fable 1 representation 
   { "Three", [10, "value"] }, // Fable 1
   [ "Two", 30 ],  // Fable 2 representation
   "One" 
]
"""
|> Json.parseAs<Value list>
|> (=) [ Two 20; Three (10, "value") Two 30; One ] // true
```
The converter should handle everything you throw at it basically. Does this answer your question?

> can I fiddle with the way DUs get serialized and deserialized,

No, there is no support for custom deserialization, however, you can still generate the `Json` tree structure by hand and serialize that to get the JSON shape you want. 

> is there some special support for option types (e.g. does null automatically get converted into None when parsing and vice versa when stringifying).

Yes, record fields of type `Option<T>` can either be omitted from the JSON object or be just `null` in which case they will get deserialized to `None`, if you are interested in how this is done, you can take a look in the [converter code](https://github.com/Zaid-Ajaj/Fable.SimpleJson/blob/master/src/Json.Converter.fs#L80), I believe it is quite readable  ;) 

I will leave this issue open until I update the docs, till then feel free to ask more questions if you have any
