### ISSUE TITLE
Issues in WebWorker

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Fable.SimpleJson#26]
I am using Fable.Remoting inside a WebWorker.

Inside the worker, ``window`` is not defined.

![grafik](https://user-images.githubusercontent.com/4236651/54937773-5b8f1a00-4f25-11e9-9100-1e89e680c109.png)

This causes two issues:

1) during deserialization, a large number of exceptions is thrown.

__Can ``isBrowser()`` be evaluated once and then cached?__

2) Fable expects ``byte array`` to be a typed array, but when executed in a web-worker, it takes the Node path and returns an untyped array. Some array operations then throw exceptions.

Workaround for 2:

```f#
let ms : byte array = ... // received over Fable.Remoting
let ms = ms |> Array.toSeq |> Seq.toArray
```

For detecting whether the script is executing inside a Web Worker, I found this (untested) stackoverflow: https://stackoverflow.com/a/18002694/1872399

**Comment by 0x53A** [comment]
I think the fix for 2) would be something like ``Uint8Array.from(...)``

**Comment by Zaid-Ajaj** [comment]
Hi @0x53A, I think the fix for 2) would be to use `Convert.FromBase64String` both when inside the browser and a worker because Afaik Fable generates typed arrays from that. As for `isBrowser()` I think it is safe to evaluate once:
```fs
module Convert =
    [<Emit("new Function(\"try {return this===window;}catch(e){ return false;}\")")>]
    let internal isBrowser : unit -> bool = jsNative

    let insideBrowser = isBrowser()

    [<Emit("typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope")>]
    let internal insideWorker :  bool = jsNative
```
then 
```fs
match elemType with
| TypeInfo.Byte ->
    if insideWorker || insideBrowser
    then unbox (Convert.FromBase64String value)
    else unbox (Node.bytesFromBase64 value)
```

**Comment by Zaid-Ajaj** [comment]
Just published a new version of Fable.Remoting.Client: `5.1.0-beta` -> `5.1.1-beta` with this quick fix. Can you please update to whether the issue is resolved? 

If that is not the case, I will need to investigate this more thoroughly and probably write some tests to run inside workers too

**Comment by 0x53A** [comment]
Thank you for (as always) your quick response.

I can't update my project because of the new Fable.Core 3.

It breaks a few things, and I haven't yet had time to investigate what exactly they renamed, changed, removed, ...

Planned to do that end of this week, then I'll update Fable.Remoting.Client asap.

But the code looks good, and I did test in a browser console that ``typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope`` works (false in main thread, true in a worker).
