### ISSUE TITLE
Server-side counterpart

### ISSUE THREAD

**Issue by kspeakman** [Zaid-Ajaj/Fable.SimpleJson#27]
Hi @Zaid-Ajaj,

I'm looking for the server-side counterpart to this library. I saw from [this issue](https://github.com/Zaid-Ajaj/FSharp.SimpleJson/issues/1) that Fable.Remoting.Json is used for that. Am I correct in assuming I just use Newtonsoft.Json but use the FableJsonConverter with it? Like this:

```fsharp
let settings =
    let s = new JsonSerializerSettings()
    s.Converters.Add(new FableJsonConverter())
    ... // other settings
    s

let myObject = JsonConvert.DeserializeObject<MyObject>(jsonString, settings)
```

Then I use try/catch to convert exceptions to Result like normal with Newtonsoft.

Thanks,

Kasey

**Comment by Zaid-Ajaj** [comment]
Hello Kasey, 

Indeed, Fable.Remoting.Json is the package you need and you can simply use the `FableJsonConverter`.

There is a little catch however when it comes to `DateTimeOffset`. It is a silly bug in Newtonsoft.Json itself, if you want to correctly convert `DateTimeOffset` back and forth then you have to add `DateParseHandling = DateParseHandling.None` to your settings.  (see [Remoting/#110](https://github.com/Zaid-Ajaj/Fable.Remoting/pull/110) to learn more) 

Hope this helps!

Zaid

**Comment by kspeakman** [comment]
Good to know, thanks! I try to avoid sending those to JS anyway, so should not be a problem.

I really like your approach with this library. Thanks!

Kasey
