### ISSUE TITLE
Can you please bump this library to Fable latest ?

### ISSUE THREAD

**Issue by kunjee17** [Zaid-Ajaj/Fable.SimpleJson#28]
Hi there is some breaking changes in fable next version. And because of that Fable.Remoting is not working. It would be great if you can bump up this version to Fable.latest. Please. :)

**Comment by Zaid-Ajaj** [comment]
Hello @kunjee17, both this library and Fable.Remoting.Client are published to latest Fable for quite some time now:
```
Fable.Remoting.Client 5.3.0-beta
  |
  | -- Fable.SimpleJson 3.1.1-beta
```
Just to be sure I update fable-compiler to latest 2.2.3 and loader to 2.1.6 with which I run my tests and everything works as expected. 

Can you elaborate what exactly isn't working?

**Comment by kunjee17** [comment]
@Zaid-Ajaj so dumb of me. My Fable.Remoting.Client is still not having beta version. Sorry sir. Let me have a look. If it still doesn't work I ll reopen the issue.

**Comment by kunjee17** [comment]
@Zaid-Ajaj It is working again. That is the only one thing where I forgot to put prerelease. Sorry man.

**Comment by Zaid-Ajaj** [comment]
No problem man! Glad to hear it is working. let me know if any problem come up :smile:
