### ISSUE TITLE
Client side performance: deserialization

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Fable.SimpleJson#30]
Continuation of https://github.com/Zaid-Ajaj/Fable.Remoting/issues/127

Deserializing the same (well, similar) data on the client takes 17.7 seconds. My own processing afterwards takes 3.3 seconds, so from a user perspective, if serialization costs were completely eliminated, it would reduce time from 21 seconds to ~4 seconds.
(Tbh I doubt similar savings to the server side are possible, but you never know)

__Note: the 21 seconds are under the profiler. It is actually much faster without the attached profiler.__

Taking a useful performance trace is a bit harder than on .NET (or maybe I'm just not used to it).

![image](https://user-images.githubusercontent.com/4236651/62233672-50fbfa00-b3c9-11e9-82dc-3ae72545c700.png)

``SimpleJson.parseNative`` takes 2.1 seconds.  
``Convert.fromJsonAs`` takes 15.6 seconds.

This is the hot path:

![image](https://user-images.githubusercontent.com/4236651/62235322-fbc1e780-b3cc-11e9-9f20-f41bc3f4bd49.png)

Note the 57% of ``createTypeInfo``.

I think it would be best to at first focus on this.

I'm currently scanning through the client code, but I think it might be possible to just cache that somewhere? What do you think?

**Comment by 0x53A** [comment]
I added a warm-up so that when the actual trace runs, the code is already jitted and the cache is already populated.

----

![image](https://user-images.githubusercontent.com/4236651/62300344-e6a19300-b476-11e9-8782-bcf7c5ca9c64.png)

So 67,77% is actually 100%, the rest is stuff happening before/after the deserialization.

---

Even with the populated cache, ``createTypeInfo`` takes 21% of total time:

![image](https://user-images.githubusercontent.com/4236651/62300479-28323e00-b477-11e9-9933-ea758ddd3d66.png)

Apparently, it is called _a lot_ and dictionary lookup is somewhat slow.

My guess would be that's because of the delayed calls (``fun () -> createTypeInfo``), I'll check if converting them to ``lazy`` helps.

**Comment by 0x53A** [comment]
Ohhh, nice, the lazy (https://github.com/0x53A/simple-json-benchmarks/commit/734bff82b3e485e453a7e623a8eac5bc51527531) really helps:

![image](https://user-images.githubusercontent.com/4236651/62301467-fc17bc80-b478-11e9-8656-082931461593.png)

**Comment by Zaid-Ajaj** [comment]
You can also try an object literal instead of a dictionary for caching, maybe it is faster:
```fs
// create the cache, creates an empty { }
let cache = obj() 

/// checks whether an object contains a key
[<Emit("$0 in $1")>] 
let isKeyIn (key: string) (o: obj): bool = jsNative

[<Emit("$1[$0]")>]
let getProp (key: string) (o: obj) : obj = jsNative

[<Emit("$2[$0] = $1")>]
let setProp (key: string) (value: obj) (o: obj) : obj = jsNative
```

**Comment by 0x53A** [comment]
It would probably be faster, but with the Lazy, ``createTypeInfo`` got lost in the noise. I can't even see it anymore in the trace. :D

I think this is it, now ``SimpleJson.parseNative`` and ``Convert.fromJson`` take roughly the same time (42% vs 57%).

``parseNative`` looks pretty bare-bones already, it basically just calls ``instanceof`` a lot.
And I also don't see anything _obvious_ in the current trace of ``Convert.fromJson``.

One issue might be garbage, it spends a lot of time inside c++

![image](https://user-images.githubusercontent.com/4236651/62303327-359df700-b47c-11e9-8525-adc1f05e935a.png)

![image](https://user-images.githubusercontent.com/4236651/62303346-3b93d800-b47c-11e9-85be-ab6997208231.png)


-----------

If anyone is interested, I created the trace with

```
node --prof node_modules\mocha\bin\mocha ./dist --timeout 50000
node --prof-process --preprocess .\isolate-0000016782B0C670-v8.log > prof.out.json
```

then opened the json file in [this viewer](https://github.com/v8/v8/tree/master/tools/profview).
