### ISSUE TITLE
Cannot deserialize enum type starting from fable-compiler 2.4.4

### ISSUE THREAD

**Issue by albertwoo** [Zaid-Ajaj/Fable.SimpleJson#34]
This issue should be caused by the new feature in fable compiler "WIP: Feature/add enum reflection".

Reproduced code:
```fsharp

type Status =
    | On = 1
    | Off = 2

type App =
  { Id: int
    Name: string
    Status: Status
    Progress: float option
    StartedDate: DateTime }
  static member defaultValue =
    { Id = 1
      Name = "a1"
      Status = Status.On
      Progress = Some 0.2
      StartedDate = DateTime.Now }

open Fable.SimpleJson

let simpleJson = Json.stringify App.defaultValue
Browser.Dom.console.error simpleJson
Browser.Dom.console.error(Json.parseAs<App> simpleJson)
```

Error message:
`Uncaught Error: Cannot convert 1 to ["Any",null]`

Or maybe I should submit a issue in the fable compiler repo? Because for Thoth.Json.Decode.Auto also has the same issue, but maybe the cause is different.

**Comment by Zaid-Ajaj** [comment]
Thanks a lot for filing the issue @albertwoo it is now fixed :smile: I published version 3.5.0 that includes the update. Please re-open the issue if the problem persists
