### ISSUE TITLE
Flags Enum Deserialization no longer works

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Fable.SimpleJson#38]
After updating Fable.Remoting to the latest version (which updated Fable.SimpleJson from 3.2 to 3.8), I can no longer deserialize a ``[<Flags>]`` enum with multiple bits set.

This worked before because it was just treated like an int.

I assume the issue is here: https://github.com/Zaid-Ajaj/Fable.SimpleJson/commit/83f12b8e761c7f55817ce985f40cd401243cd7ef#diff-dd3f6f39b238e426d14aaeaf582f183cR128

For a correcter validation, it would need to check whether it has the FlagsAttribute, then check either each individual bit, or the whole thing.

But to be honest, my preference would be to drop the check, because in .NET you can do

```c#
enum E {  A = 1, B = 2 }
E e = (E)0xff;
```

**Comment by Zaid-Ajaj** [comment]
Hello @0x53A, sorry for introducing the regression, it looks like I didn't have a proper test for enums with flags. Do you have an example for me that fails so I can look at it? A PR would be even better yet :smile: 

> my preference would be to drop the check

That is fine by me if it is the only way to fix this

>  it would need to check whether it has the FlagsAttribute, then check either each individual bit, or the whole thing.

We don't have access to attribute metadata in Fable :/

**Comment by 0x53A** [comment]
Hi @Zaid-Ajaj I added a test here: https://github.com/Zaid-Ajaj/Fable.SimpleJson/pull/39

**Comment by Zaid-Ajaj** [comment]
I guess it's alright in this case :smile: released v3.8.1 with the fix :rocket: thanks a lot for the PR. I will be able to patch Fable.Remoting.Client soon
