### ISSUE TITLE
SimpleJson can not parse numbers in scientific notation

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Fable.SimpleJson#40]
I had an issue where Elmish.Bridge would fail to deserialize some messages on the client.
It uses Newtonsoft on the server and Fable.SimpleJson on the client.

```f#
    testCase "Scientific notation works"<| fun _ ->
        match SimpleJson.tryParse "-4.5474735088646412E-13" with
        | Some _ -> () // ok
        | None -> test.failwith "SimpleJson.tryParse failed"
```

**Comment by Zaid-Ajaj** [comment]
Hello @0x53A, internally Elmish.Bridge should use `tryParseNative` and `parseNative` and these . The `tryParse` are handwritten JSON parsers using parser combinators and will likely be deprecated in the future (or maybe I will implement scientific  for them). In the meanwhile, use the native parsing functionality

**Comment by 0x53A** [comment]
The issue was fixed in Elmish.Bridge.
