### ISSUE TITLE
Cannot parse single long lines of JSON input

### ISSUE THREAD

**Issue by dbrattli** [Zaid-Ajaj/Fable.SimpleJson#46]
Looks like Fable.SimpleJson cannot parse single long lines of JSON input. When parsing JSON input of 310907 chars it fails with: "Could not parse the JSON input: ...". If I reformat the the same input into 11243 lines, then the parsing is succeeds. Is there a max input limitation somewhere? JSON example can be provided on request.

**Comment by Zaid-Ajaj** [comment]
Hi @dbrattli, which function are you using to parse the Json? (you should use `Json.parseNativeAs<'t>`)

**Comment by dbrattli** [comment]
I used `Json.parse` as I had to use `SimpleJson.mapKeys`. Switched to `Json.parseNative` and now it work like a charm. Thanks for the quick response!

**Comment by Zaid-Ajaj** [comment]
No problem, `Json.parse` will go away in the next major release :smile:
