### ISSUE TITLE
Being asked to reference Fable.Parsimmon in F# script

### ISSUE THREAD

**Issue by DavidSSL** [Zaid-Ajaj/Fable.SimpleJson#48]
In my .fsx file, I've got

``` fsharp
#r "/home/david/.nuget/packages/fable.simplejson/3.9.0/lib/netstandard2.0/Fable.SimpleJson.dll"
#r "/home/david/.nuget/packages/fable.simplehttp/3.0.0/lib/netstandard2.0/Fable.SimpleHttp.dll"
#r "/home/david/.nuget/packages/fable.parsimmon/4.1.0/lib/netstandard2.0/Fable.Parsimmon.dll"
open Fable.SimpleHttp
open Fable.SimpleJson
open Fable.Parsimmon.Parsimmon
open Fable.Parsimmon

type Photo =
       { url: string
         size: int
         title: string }

"
  {
    \"url\": \"1.jpeg\",
    \"size\": 36,
    \"title\": \"Beachside\"
  }
"
|> Json.parseAs<Photo>
```

However, when I try to run the code in fsi, I get:
```
error FS0074: The type referenced through 'Fable.Parsimmon.Parsimmon' is defined in an assembly that is not referenced. You must add a reference to assembly 'Fable.Parsimmon'.
```
Here's my set up info

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.805 [/usr/share/dotnet/sdk]
  3.1.101 [/usr/share/dotnet/sdk]
  3.1.103 [/usr/share/dotnet/sdk]
  3.1.201 [/usr/share/dotnet/sdk]
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

**Comment by Zaid-Ajaj** [comment]
Hi @DavidSSL, actually this library like all Fable-specific packages, doesn't work standalone inside F# script files. It can only be run and compiled using Fable so unless you are compiling the fsx files using Fable, the code won't work

**Comment by DavidSSL** [comment]
@Zaid-Ajaj . Wow thanks for this lightning fast response. Now I have to figure out how to compile the fsx script file using Fable since I am an absolute newbie at Fable. In fact, I was/am trying to create an FS Bolero app and that's how I came across you via the DevOwl. Thanks for your help

**Comment by Zaid-Ajaj** [comment]
I would say if you try out Fable, then a project structure is more reliable to work with than a script file because in any case, you won't be able to run pieces of the script individually but instead you will need to compile the entire thing. 

As for learning Fable, I wrote an entire book on the subject called [The Elmish Book](https://zaid-ajaj.github.io/the-elmish-book) :smile: 

The material used in the streams with Roman (The Dev Owl) is inspired by content from there.

**Comment by DavidSSL** [comment]
@Zaid-Ajaj thank you for your advice. I did indeed find your book and I believe that I've forked it. I will go through it after I'm done with [Elm in Action](https://www.manning.com/books/elm-in-action). Basically I'm replicating what's done in the latter and then trying to "port" it to FsBolero. But definitely will go through your book afterwards and really enjoyed the series you did with Roman
