### ISSUE TITLE
Error: The type initializer for '<StartupCode$Fable-SimpleJson>.$Parser' threw an exception.

### ISSUE THREAD

**Issue by DavidSSL** [Zaid-Ajaj/Fable.SimpleJson#49]
I get the error referenced in the title with the following code:

``` fsharp
type Message =
  | GotPhotos of Result<List<Photo>,int>
  | GotPhotosError of exn

type Photo =
  { url: string
    size: int
    title: string }

let getData ()=
  async{
    let! (statusCode, _) = Http.get "http://elm-in-action.com/photos/list.json"
    match statusCode with
    | 200 ->
      let jsonResponse =
        "
          {
            \"url\": \"2.jpeg\",
            \"size\": 19,
            \"title\": \"Epica, live at the Agora\"
          }
        "
        |> Json.parseAs<Photo>
        
      return Ok [jsonResponse]
    | _ -> return Result.Error statusCode
  } 

Program.mkProgram (fun _ -> initModel, Cmd.batch [Cmd.ofAsync getData () GotPhotos GotPhotosError;Cmd.ofMsg GetSignedInAs]) update view |> Program.withRouter router
```
This is an FS Bolero App but since this is failing with this particular library, I believe I'm doing the right thing posting this here. 

I get the feeling it's something simple and obvious but I don't see what it could be.

**Comment by Zaid-Ajaj** [comment]
Hi @DavidSSL, it seems that you are trying to use this library in FsBolero. Unfortunately that will not work because this library is specifically built to work with the Fable compiler. FsBolero and Fable are entirely different runtimes and using one library in the other won't work. 

I believe for FsBolero, you can use whatever people use F# on dotnet with Newtonsoft.Json and HttpClient instead of using Fable libraries.

**Comment by DavidSSL** [comment]
Hi @Zaid-Ajaj thanks again for your prompt answer. That's a real shame. FYI, Fable.SimpleHttp does work with FsBolero though.

**Comment by Zaid-Ajaj** [comment]
Yeah only a subset of the functionality of SimpleHttp works in .NET but that an internal feature really to make building Fable type providers easier ;)

**Comment by DavidSSL** [comment]
Sounds like I still have a lot to learn...
