### ISSUE TITLE
Stringify with Nagareyama

### ISSUE THREAD

**Issue by kerams** [Zaid-Ajaj/Fable.SimpleJson#55]
I have noticed a problem with `stringify` when migrating to Nagareyama.

https://github.com/Zaid-Ajaj/Fable.SimpleJson/blob/762ae4140c0104f8d776e11117637c50ca320f3d/src/SimpleJson.fs#L65-L84

I'm getting `Uncaught TypeError: Cannot read property '' of undefined` from within the replacer function `get key jsThis`. Indeed, when I evaluated `JSON.stringify({ v: 50, s: 'nope' }, (k, v) => { console.log(k); return v; });` in the console, an empty string is printed first. https://stackoverflow.com/a/16329124/2710074 suggests this is normal.

Not sure if this is a result of me getting rid of Babel or some internal changes in Fable, but I reckon the fix (immediately check if `k` is null or empty and then return `v`?) should land here because it feels like this function almost worked by chance under Fable 2.

**Comment by Zaid-Ajaj** [comment]
Hi @kerams, I should have probably documented it but starting from Fable 3, you should use Json.serialize which relies on Reflection for serialization

**Comment by kerams** [comment]
The problem originates in Remoting. Is it possible to swap the functions there and have it work for both Fable 2 and 3?

**Comment by Zaid-Ajaj** [comment]
Do you have latest Fable.Remoting.Client?

Remoting client v7.0.1 already uses Json.serialize and should work ootb with both Fable 2 & 3. Even the integration tests are compiling the tests for both compiler versions.

**Comment by kerams** [comment]
I do. The stack looks like this:

https://github.com/Zaid-Ajaj/Fable.SimpleJson/blob/f8ba06da1967eba5f5c14c7f9e6259fdf9224659/src/Json.Converter.fs#L813
https://github.com/Zaid-Ajaj/Fable.SimpleJson/blob/f8ba06da1967eba5f5c14c7f9e6259fdf9224659/src/Json.Converter.fs#L801
https://github.com/Zaid-Ajaj/Fable.Remoting/blob/8ceb6485a81b030937ca2e770a6a7560e46e0c87/Fable.Remoting.ClientV2/Proxy.fs#L134

I think it comes down to the fact that the request type is a class like this:

```fsharp
type Request (v: int64) =
    member _.Version = v

type Request<'a> (v: int64, a: 'a) =
    inherit Request (v)

    member _.Actual = a

type Api = {
    getCategoriesNu: Request<unit> -> Async<Response<CategoryRendition []>>
}
```

**Comment by Zaid-Ajaj** [comment]
That's interesting @kerams because class support was never a feature 😅 I guess it worked by chance in Fable 2.x because you only serializing the data to the backend and Fable had compiler-generated `.toJSON()` from the class declaration which gets called internally by the native `JSON.stringify` when available. 

However, if you used a class as output/return-type, SimpleJson would never know how to properly construct an instance because class metadata (constructor and whatnot) are not available. 

> At least that's what I think, if `Response<'t>` that you are using above is a class, I would be really surprised

**Comment by Zaid-Ajaj** [comment]
BTW, you are seeing `SimpleJson.stringify value` in the call stack because when SimpleJson doesn't know how to serialize a type, it falls back to the native `JSON.stringify`, that is the best it can do when the metadata are not known or supported.

**Comment by kerams** [comment]
Yeah, the fallback is fair enough. However, the function in the OP will always fail (Fable 3) when `value` is a JS object. The check I suggested could remedy that and my class woes by extension :). I could give it a shot.

**Comment by Zaid-Ajaj** [comment]
> However, the function in the OP will always fail (Fable 3) when value is a JS object

How come? I don't think I changed the function itself when I added Fable 3 support with Json.serialize 🤔 

Isn't it possible for you to use a record/union as input too instead of classes?

**Comment by kerams** [comment]
Actually, it might not be as much a problem with the empty `key`, but with the fact that `this` is undefined when I place a breakpoint in the replacer function.

```js
function SimpleJson_stringify(value) {
    if (value == null) {
        return JSON.stringify(null);
    }
    else {
        return JSON.stringify(value, (key, v) => {
            let copyOfStruct;
            if (InteropUtil_isDateOffset((this)[key])) {
                const dateOffset = (this)[key];
                return (0,_fable_library_3_0_0_nagareyama_beta_003_Date_js__WEBPACK_IMPORTED_MODULE_5__.toString)(dateOffset, "O");
            }
            else if (InteropUtil_isBigInt((this)[key])) {
                const bigInt = (this)[key];
                return (0,_fable_library_3_0_0_nagareyama_beta_003_Decimal_js__WEBPACK_IMPORTED_MODULE_6__.toString)((0,_fable_library_3_0_0_nagareyama_beta_003_BigInt_js__WEBPACK_IMPORTED_MODULE_7__.toDecimal)(bigInt));
            }
            else {
                return ((typeof v) === "string") ? v : ((0,_fable_library_3_0_0_nagareyama_beta_003_Util_js__WEBPACK_IMPORTED_MODULE_8__.isIterable)(v) ? (Array.isArray(v) ? v : (Array.from(v))) : (InteropUtil_isBigInt(v) ? (0,_fable_library_3_0_0_nagareyama_beta_003_Decimal_js__WEBPACK_IMPORTED_MODULE_6__.toString)((0,_fable_library_3_0_0_nagareyama_beta_003_BigInt_js__WEBPACK_IMPORTED_MODULE_7__.toDecimal)(v)) : (InteropUtil_isDateOffset(v) ? (copyOfStruct = v, (0,_fable_library_3_0_0_nagareyama_beta_003_Date_js__WEBPACK_IMPORTED_MODULE_5__.toString)(copyOfStruct, "O")) : v)));
            }
        }, (0,_fable_library_3_0_0_nagareyama_beta_003_Option_js__WEBPACK_IMPORTED_MODULE_9__.some)(0));
    }
}
```

Since it is undefined, `if (InteropUtil_isDateOffset((this)[key]))` always throws for me. I can only speculate why this all happens because I know too little about JS.

> Isn't it possible for you to use a record/union as input too instead of classes?

Theoretically sure, but I've put custom code into the Remoting proxy on the server which checks whether `Request.Version` is equal to the server version (if it isn't, the server returns a response that basically triggers a tab refresh, causing the SPA to update). In order to this, I need that base class to be able to cast to, though I'll check if it's solvable with records and some SRTP magic.

**Comment by Zaid-Ajaj** [comment]
> Isn't v the same thing?

According to PR #54 sent by Alfonso to upgrade to Fable 3, it seems to be the case. I will give it a try to fix it for Fable 3 code. However, it is probably a better idea to still use records because ideally you want even the nested generic type to go through the more reliable `Json.serialize` function and not through the catch-all `JSON.stringify` because `JSON.stringify` will sometimes serialize internal JS runtime representation of F# types (Maps and Sets are trees internally in latest Fable) and the backend won't handle all of those representations.

> though I'll check if it's solvable with records and some SRTP magic

Well, you can implement an interface `IRequest` with `Version` member that returns the `Version` field of the record:
```fs
type IRequest = 
  abstract Version : unit -> int64 

type Request<'t> = 
  { Version: int64; Content: 't }
  interface IRequest with
    member instance.Version() = instance.Version
```
I don't know how complicated your backend is, but even having a simple function could work across generic versions of `Request<'t>`
```fs
let version (request: Request<_>) = request.Version
```
As for the noise on the front-end, can't replace the class constructor with a static `Create(version, content)` function of the `Request<'t>` and basically have the same thing?

**Comment by kerams** [comment]
SRTP turned out to be a non-starter, but your suggestion is very clever and works like a charm.

Thanks and feel free to close this if you decide not to do anything more.

**Comment by Zaid-Ajaj** [comment]
> Instead, I've added extra code to Remoting at the point where the request is deserialized and the check above is done once for every API function there is and will be. Sort of like a middleware, but it is literally in the middle of Remoting

The way I would do it would be the same way of doing authenticated or authorized requests where you have a piece of logic that you don't you want to repeat:
```fs
[<RequireQualifiedAccess>] 
module Require

let version (request: Request<_>) = request.Version

let sameVersion serverVersion (handler: Request<_> -> Async<Response<_>> = 
  fun request -> async {
      if version request <> serverVersion then
        return Response.OldVersion
      else
        return! handler request 
  }
```
Then use the module like this
```fs
getCategoriesNu = Require.sameVersion serverVersion (fun request ->
   async {
        // actual body
        return Response.Ok [||]
   })
```
You probably have something similar, this is what I would use

> Thanks and feel free to close this if you decide not to do anything more.

I actually just pushed Fable.SimpleJson v3.16.1 with the fix, can you try it out? :wink:

**Comment by Zaid-Ajaj** [comment]
Variations of these "middleware" work really nicely too, for example:
```fs
let sameVersion serverVersion (handler: 'Content -> Async<'Data>) : (Request<'Content> -> Async<Response<'Data>>) = 
  fun (request: Request<_>) -> async {
      if version request <> serverVersion then
        return Response.OldVersion
      else
        let! data = handler request.Content
        return Response.Ok data 
  }
```
so that you can write:
```fs
getCategoriesNu = Require.sameVersion serverVersion (fun content ->
   async {
        // actual body
        return [| |]
   })
```
Basically abstracting away the request and response. Is what you use too?

**Comment by kerams** [comment]
You're blowing my mind here. It's a "bit" cleaner than basically keeping a fork of Fable.Remoting in your code base 🤯.

The class-based `Request` works in 3.16.1 too. Cheers again.

**Comment by Zaid-Ajaj** [comment]
An entire fork of FR 😱 I hope now you can get rid of it 🔥

**Comment by kerams** [comment]
That was an exaggeration, only the Server/Giraffe part, but I did get rid of it :).
