### ISSUE TITLE
Json.serialise compatibility with Simplejson.stringify moving to Nagareyama

### ISSUE THREAD

**Issue by tomcl** [Zaid-Ajaj/Fable.SimpleJson#57]
I am something of a newbie when it comes to dotnet, but am working on a 10K line F# electron app. So forgive this question here, and feel free to close it.

I need to replace SimpeJson.stringify with Json.serialize so it will work under fable 3.

My question is:
Is the output from Json.serialise identical to simpleJson.stringify? I need to be able to read in files of given F# type written in Json by the app under Fable 2.x.

**Comment by Zaid-Ajaj** [comment]
Hi @tomcl, I believe the output is indeed identical and the deserializer should be able to handle anything you throw at it. Let me if it doesn't 😉

**Comment by tomcl** [comment]
😊 thanks, I will.

Closable unless you wnat to leave it open for otehrs for a while.

**Comment by Zaid-Ajaj** [comment]
I will close it for now, please reopen if any issue arises 😄
