### ISSUE TITLE
Json.tryParseAs<'T> fails under Fable 3 when 'T is in different project 

### ISSUE THREAD

**Issue by tomcl** [Zaid-Ajaj/Fable.SimpleJson#58]
This is for the record a reference to Fable 3 issue:
https://github.com/fable-compiler/Fable/issues/2285

It can be worked around easily by moving the Json functions into the F# project containing the type definitions which are parsed.

The bug only appears (in my repro) on code built by electron-builder, and not on dev code. So it is not clear exactly when this will hit: presumably with some configurations of webpack. It is not related to minification.

**Comment by tomcl** [comment]
I think this issue could be closed here, because there is a related fable 3 bug #2293. It seems that nagareyama type reflection fails in some circumstances across F# projects, but only when the js output is bundled and built by `electron-builder`.: development code runs fine with electron.

**Comment by Zaid-Ajaj** [comment]
@tomcl I don't think this a SimpleJson issue since AFAIK the library doesn't distinguish code running in development and code running in production. I will close the issue for now here but I will keep an eye on the main Fable issue and maybe debug it when time permits
