### ISSUE TITLE
Fails to serialize / deserialize large, deep object hierarchies

### ISSUE THREAD

**Issue by Balinth** [Zaid-Ajaj/Fable.SimpleJson#71]
Hey guys, using Fable.Remoting, I ran into the problem where larger object trees fail to be serialized / deserialzied.

With json, serialization works, (see attached file captured from browser network tab on the client) but client side deserialization fails.

[TreeObj.txt](https://github.com/Zaid-Ajaj/Fable.SimpleJson/files/6475428/TreeObj.txt)

With binary, the serverside serialization fails, but I could not debug capture a meaningful exception, except another exception that the exception thrown itself could not be serialized.

Tried updating to latest packages (Fable.Remoting.Server (5.19) and Fable.Remoting.Client (7.9) with Fable.SimpleJson (3.19))

For the json client side deserialization, the exception is the following:

columnNumber: 11
​​​​​​​
fileName: "https://localhost:8080/app.js line 1886 > eval"
​​​​​​​
lineNumber: 431
​​​​​​​
message: "Cannot convert \"*\" to System.Char"
​​​​​​​
stack:` "toFail/<@webpack-internal:///./.fable/fable-library.2.13.0/String.js:431:11\ncreatePrinter/<@webpack-internal:///./.fable/fable-library.2.13.0/String.js:525:74\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:2475:42\nclo1$$7/<@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1301:46\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1303:67\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$1@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1244:50\nmapping$$1@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:368:14\nmap@webpack-internal:///./.fable/fable-library.2.13.0/Array.js:367:22\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1241:131\nmapping$$5@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1892:46\nmap/xs$$32<@webpack-internal:///./.fable/fable-library.2.13.0/List.js:469:63\nfold@webpack-internal:///./.fable/fable-library.2.13.0/List.js:254:23\nmap@webpack-internal:///./.fable/fable-library.2.13.0/List.js:468:20\nConvert$$$fromJsonAs/_ret4<@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1891:123\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1897:36\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1195:72\nclo1$$7/<@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1301:46\nConvert$$$fromJsonAs@webpack-internal:///./.fable/Fable.SimpleJson.3.19.0/Json.Converter.fs:1303:67\nProxy$$$proxyFetch/</</</</</</</</</<@webpack-internal:///./.fable/Fable.Remoting.Client.7.9.0/Proxy.fs:307:155\nonSuccess@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:259:17\narg00/xhr.onreadystatechange@webpack-internal:///./.fable/Fable.Remoting.Client.7.9.0/Http.fs:185:24\nEventHandlerNonNull*arg00@webpack-internal:///./.fable/Fable.Remoting.Client.7.9.0/Http.fs:168:9\nfromContinuations/<@webpack-internal:///./.fable/fable-library.2.13.0/Async.js:139:12\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nonSuccess@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:259:20\ncancellationToken/<@webpack-internal:///./.fable/fable-library.2.13.0/Async.js:118:16\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nprotectedBind/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:256:16\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nDelay/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:297:27\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nprotectedBind/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:256:16\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nDelay/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:297:27\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nprotectedBind/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:256:16\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nDelay/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:297:27\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\ncatchAsync/<@webpack-internal:///./.fable/fable-library.2.13.0/Async.js:124:9\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nprotectedBind/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:256:16\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nDelay/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:297:27\nprotectedCont/<@webpack-internal:///./.fable/fable-library.2.13.0/AsyncBuilder.js:247:10\nstartWithContinuations@webpack-internal:///./.fable/fable-library.2.13.0/Async.js:178:14\nstart@webpack-internal:///./.fable/fable-library.2.13.0/Async.js:166:10\nstartImmediate@webpack-internal:///./.fable/fable-library.2.13.0/Async.js:169:10\nCmd$002EOfAsync$$$start/<@webpack-internal:///./.fable/Fable.Elmish.3.1.0/cmd.fs:188:90\nTrigger/<@webpack-internal:///./.fable/fable-library.2.13.0/Event.js:75:16\niterate/<@webpack-internal:///./.fable/fable-library.2.13.0/Seq.js:664:13\nfold@webpack-internal:///./.fable/fable-library.2.13.0/Seq.js:559:15\niterate@webpack-internal:///./.fable/fable-library.2.13.0/Seq.js:663:7\nTrigger@webpack-internal:///./.fable/fable-library.2.13.0/Event.js:74:60\nset/this._timeoutId<@webpack-internal:///./.fable/fable-library.2.13.0/Timer.js:68:30\nsetTimeout handler*set@webpack-internal:///./.fable/fable-library.2.13.0/Timer.js:60:31\nTimer$$$delay@webpack-internal:///./.fable/Fable.Elmish.3.1.0/prelude.fs:24:3\nCmd$002EOfAsync$$$start@webpack-internal:///./.fable/Fable.Elmish.3.1.0/cmd.fs:187:68\nCmd$002EOfAsyncWith$$$either/<@webpack-internal:///./.fable/Fable.Elmish.3.1.0/cmd.fs:119:10\nmapping/<@webpack-internal:///./.fable/Fable.Elmish.3.1.0/cmd.fs:49:8\nmapping/<@webpack-internal:///./.fable/Fable.Elmish.3.1.0/cmd.fs:49:8\naction@webpack-internal:///./.fable/Fable.Elmish.3.1.0/cmd.fs:35:11\niterate/<@webpack-internal:///./.fable/fable-library.2.13.0/List.js:522:10\nfold@webpack-internal:///./.fable/fable-library.2.13.0/List.js:254:23\niterate@webpack-internal:///./.fable/fable-library.2.13.0/List.js:521:7\nCmd$$$exec@webpack-internal:///./.fable/Fable.Elmish.3.1.0/cmd.fs:33:80\n_loop@webpack-internal:///./.fable/Fable.Elmish.3.1.0/program.fs:176:69\ndispatch@webpack-internal:///./.fable/Fable.Elmish.3.1.0/program.fs:189:9\nmapSetState/<@webpack-internal:///./src/Client/Client.fs:872:16\nsubPageView/<@webpack-internal:///./src/Client/Client.fs:635:18\nview/button<@webpack-internal:///./src/Client/Query.fs:253:13\ncallCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:188:14\ninvokeGuardedCallbackDev@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:237:16\ninvokeGuardedCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:292:31\ninvokeGuardedCallbackAndCatchFirstError@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:306:25\nexecuteDispatch@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:389:42\nexecuteDispatchesInOrder@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:414:20\nexecuteDispatchesAndRelease@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3278:29\nexecuteDispatchesAndReleaseTopLevel@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3287:10\nforEachAccumulated@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3259:8\nrunEventsInBatch@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3304:21\nrunExtractedPluginEventsInBatch@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3514:19\nhandleTopLevel@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3558:36\nbatchedEventUpdates$1@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21871:12\nbatchedEventUpdates@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:795:12\ndispatchEventForLegacyPluginEventSystem@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3568:24\nattemptToDispatchEvent@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4267:44\n"`

**Comment by Zaid-Ajaj** [comment]
Hi there @Balinth thanks for filing the issue, I think it _might_ have to do with the fact that you are using `char`, can you use `string` where you use `char` and see if it fixes the problem? In the meantime, I will try to reproduce the problem

**Comment by Balinth** [comment]
Thanks for the lightning fast response, and you thought right to boot!

Not sure if it helps, but just not sending the union cases with char fields is not enough, it only works if there was no char field whatsoever in the target DU type.

**Comment by Zaid-Ajaj** [comment]
Fixed as of Fable.SimpleJson v3.20 🚀 it will be available in a bit once nuget indexes it, could you give it a try then? Please reopen the issue if the problem persists. I will update Fable.Remoting.Client too

**Comment by Zaid-Ajaj** [comment]
Fable.Remoting.Client v7.10 has been published and it includes SimpleJson 3.20

**Comment by Balinth** [comment]
Updated the libs and it indeed solved the problem 👍
