### ISSUE TITLE
Effectivly uses eval

### ISSUE THREAD

**Issue by NicoVIII** [Zaid-Ajaj/Fable.SimpleJson#80]
I'm working on an browser extension in F# with Fable where the default CSP does not allow the use of eval and warns about it.

In this library is one place (Json.Converter.fs), where it generates basically eval (new Function = eval afaik) and therefore I had to allow that in CSP what I don't want to do.
The web-ext linter tool says this:

> Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.

Is there a way to make this lib CSP compliant by removing this eval? I'm not sure if there is a better way to determine, if we are in a browser or not.

**Comment by Zaid-Ajaj** [comment]
Hi @NicoVIII, I will see if there is a better way to fix the issue.

**Comment by Zaid-Ajaj** [comment]
@ThisFunctionalTom A PR would be great! These days I am low on time to do OSS in full capacity but I can review/merge/publish when I can 😄
