### ISSUE TITLE
Is Fable.SimpleJson supposed to work with Fable 3 ?

### ISSUE THREAD

**Issue by pkese** [Zaid-Ajaj/Fable.SimpleJson#96]
I tried using this in a project with Fable 3, but it's complaining that [Fable.Import](https://github.com/Zaid-Ajaj/Fable.SimpleJson/blob/73eb5aed779bc6c4a5efb90d796e87d96e7e5a29/src/SimpleJson.fs#L6) is not available.

**Comment by pkese** [comment]
Quite interesting:  
if I just remove that particular line, it seems to work fine and unit tests pass.

**Comment by pkese** [comment]
Apparently there was something wrong with my paket / TargetFramework / other dependencies.
If I create empty project with Fable 3 it works fine.

**Comment by DamianReeves** [comment]
I get the same issue with Fable 4.
